### ISSUE TITLE
Cohort A breakout group text

### ISSUE THREAD

**Issue by holdenharris-NOAA** [nmfs-openscapes/2024-nmfs-champions#101]
Test issue...

Thanks for the help, @KatGodwin-NOAA @masonsmith-noaa

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
