### ISSUE TITLE
We need more fish-based emojis

### ISSUE THREAD

**Issue by LorenStearmanNOAA** [nmfs-openscapes/2024-nmfs-champions#102]
Votes for new fish-based emojis? @GaitlynMalone-NOAA 

- [ ] Sockeye Salmon
- [x] Banded Sculpin
- [x] Pacific Lamprey
- [ ] Striped Bass
- [ ] Atlantic Salmon

**Comment by eeholmes** [comment]
![image](https://github.com/user-attachments/assets/c8a29d6e-8725-4eaa-839d-c9e5d4dd7a1a)

**Comment by RyanRykaczewski-NOAA** [comment]
I vote for some forage fishes!

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
