### ISSUE TITLE
Testing raising an issue.

### ISSUE THREAD

**Issue by RyanRykaczewski-NOAA** [nmfs-openscapes/2024-nmfs-champions#103]
Ok... am I doing this right?

**Comment by stefaniebutland** [comment]
yep!

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
