### ISSUE TITLE
I get too many emails

### ISSUE THREAD

**Issue by MattCallahan-NOAA** [nmfs-openscapes/2024-nmfs-champions#106]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the debugging guide: <https://github.com/Openscapes/2021-noaa-nmfs/wiki/2-Issues-and-Project-Boards>
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue isn't already filed.

### Description

I get too many emails from this repo

### Steps to Reproduce

1. anyone does anything
2. an email shows up in my inbox
3. 👎 

**Expected behavior:**

- Someone does something
- I do not get an email

**Actual behavior:**

See steps to reproduce

**Comment by eeholmes** [comment]
![image](https://github.com/user-attachments/assets/5ab9f822-ac05-4bae-bef7-2d322c4b2e21)

**Comment by MattCallahan-NOAA** [comment]
mic drop cat
