### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by tracymercer-noaa** [nmfs-openscapes/2024-nmfs-champions#11]
##HELP

- [ ] how do I do this thing
- [ ] i don't know what to write

@Ashley-Trudeau-NOAA

**Comment by Ashley-Trudeau-NOAA** [comment]
You're doing great!

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
