### ISSUE TITLE
insert link 

### ISSUE THREAD

**Issue by MallarieYeager-NOAA** [nmfs-openscapes/2024-nmfs-champions#112]
hey @SRBayer  can you insert the link for our description

**Comment by SRBayer** [comment]
Inserted hyperlink for our description!

**Comment by SRBayer** [comment]
ok but we need to reopen this issue, the names still need to be added @masonsmith-noaa

**Comment by masonsmith-noaa** [comment]
names added. @Molly-Zaleski please review

**Comment by Molly-Zaleski** [comment]
All set, team!
