### ISSUE TITLE
Halloween issues

### ISSUE THREAD

**Issue by chomweaverNOAA** [nmfs-openscapes/2024-nmfs-champions#114]
What should I be for Halloween?

- [x] #116
- [ ] Cat

**Comment by chomweaverNOAA** [comment]
## Hello

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, tell us what you were for Halloween, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
