### ISSUE TITLE
Add a cute image of a pet or animal to your md file?

### ISSUE THREAD

**Issue by brian-lieb** [nmfs-openscapes/2024-nmfs-champions#13]
In the markdown file associated with your user, can you upload and add an image of a pet or other cute animal to the file instead of the stock image they added earlier?

- @JZeh1 
- @emmonsca

**Comment by JZeh1** [comment]
![whale](https://github.com/user-attachments/assets/f5920a8e-6972-42e1-95f2-cff26c18f908)
