### ISSUE TITLE
help with stuff

### ISSUE THREAD

**Issue by smchinn** [nmfs-openscapes/2024-nmfs-champions#15]
@CrystalDombrow-NOAA 
@j-m-lindsay 

learning about Issues!

1. what is our first step?
2. what do we do next?

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
