### ISSUE TITLE
Practice

### ISSUE THREAD

**Issue by KelsiFurman-NOAA** [nmfs-openscapes/2024-nmfs-champions#16]
Practicing making an issue

1. Created blank issue
2. Shared with breakout group

Breakout group:
@amandalbradford
@chomweaverNOAA

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
