### ISSUE TITLE
Request for Data Upload

### ISSUE THREAD

**Issue by KateOverly-NOAA** [nmfs-openscapes/2024-nmfs-champions#17]
@rebecca-vanhoeck could you please upload XX dataset to the [here](https://github.com/nmfs-openscapes/2024-nmfs-champions)

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
