### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by ElizabethMPhillips** [nmfs-openscapes/2024-nmfs-champions#19]
I am having an issue with this screenshot from my computer...

![image](https://github.com/user-attachments/assets/f71d6b5a-7926-4d8b-a6f9-e428c74e1f5a)

@EmilyMarkowitz-NOAA or @SRBayer can you help?

**Comment by EmilyMarkowitz-NOAA** [comment]
Your screenshot looks great! Great job
![download](https://github.com/user-attachments/assets/aa9cbc9f-108f-4da1-a664-c9c72d6511d3)
!

**Comment by SRBayer** [comment]
Looks good! 
![download](https://github.com/user-attachments/assets/bd0b33b9-ea01-4247-a9d1-26c26e0c2059)
