### ISSUE TITLE
please fix these issues

### ISSUE THREAD

**Issue by pingercod** [nmfs-openscapes/2024-nmfs-champions#20]
Fix thsee tyops @hwfennie 
edit [hyperlinks](https://www.google.com/) @somros

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
