### ISSUE TITLE
Test issue BR 9

### ISSUE THREAD

**Issue by somros** [nmfs-openscapes/2024-nmfs-champions#21]
This is a **_test_**

- [x] do this @pingercod 
- [x] do that @hwfennie

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
