### ISSUE TITLE
Breakout group issue

### ISSUE THREAD

**Issue by LG-Smith** [nmfs-openscapes/2024-nmfs-champions#22]
Trying out tagging @mitchrider and @lmdewitt 

🥇

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
