### ISSUE TITLE
Ice cream flavor

### ISSUE THREAD

**Issue by VikramKhurana-NOAA** [nmfs-openscapes/2024-nmfs-champions#23]
@cberchok Bringing these issues to your attention
Which ice cream flavor do you like?

- [ ] Vanilla
- [x] Chocolate
- [ ] Strawberry

**Comment by ElizabethMPhillips** [comment]
You didn't include chocolate chip mint! 🍨 🍃 🍫

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
