### ISSUE TITLE
Parent issues and sub-issues

### ISSUE THREAD

**Issue by mariechill** [nmfs-openscapes/2024-nmfs-champions#24]
On the GitHub help page it talks about Parent Issues and Sub-issues as a way to track items. Does anyone know if this is actually possible to use or request on the NOAA enterprise site?

- [x] #38
- [x] #39
- [x] #40
- [ ] 

@owenrliu 
@alexjensen-NOAA

**Comment by jules32** [comment]
- [ ] thing
- [ ] thing
- [ ] thing
- [ ]

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
