### ISSUE TITLE
Help with Turtles

### ISSUE THREAD

**Issue by AHarmon-NOAA** [nmfs-openscapes/2024-nmfs-champions#26]
Can you tell me what this?

- [x] Green Sea Turtle
- [ ] Loggerhead
- [ ] Olive Ridley
- [ ] Not a Turtle!

@MarylouStaman-NOAA

**Comment by MarylouStaman-NOAA** [comment]
Green!

**Comment by jules32** [comment]
Great label!

**Comment by eeholmes** [comment]
![image](https://github.com/user-attachments/assets/65737c21-63c5-441a-902d-8765f2f68fdc)

**Comment by eeholmes** [comment]
![image](https://github.com/user-attachments/assets/bbb50d9b-091d-49de-9080-dda517f81ba5)
