### ISSUE TITLE
Practicing an issue

### ISSUE THREAD

**Issue by alexjensen-NOAA** [nmfs-openscapes/2024-nmfs-champions#27]
#### Testing creating an issue

Fake task list:

- [ ] Create a new repository @mariechill 
- [ ] Create a new readme @owenrliu

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
