### ISSUE TITLE
help with markdown

### ISSUE THREAD

**Issue by jmjech** [nmfs-openscapes/2024-nmfs-champions#28]
I don't know how to make a list in markdown.

@IsabellaGarfield : can you help!?

**Comment by IsabellaGarfield** [comment]
A list using '+':
+ First
+ second
+ third

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
