### ISSUE TITLE
Question about issues

### ISSUE THREAD

**Issue by mitchrider** [nmfs-openscapes/2024-nmfs-champions#31]
### Tasks @lmdewitt @LG-Smith
- [ ] Figure out what issues we have 
- [ ] Fix those issues

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
