### ISSUE TITLE
not enough puppies

### ISSUE THREAD

**Issue by SRBayer** [nmfs-openscapes/2024-nmfs-champions#33]
### **There are not enough puppies in this Openscape class. We need more.** 

<img width="267" alt="Capture" src="https://github.com/user-attachments/assets/94a95272-3fe5-486b-998b-ce37fd1de19e">

![Uploading funny-dog-just-saying-hi-npp3xjjzhusrvpdm.gif…]()

**Comment by EmilyMarkowitz-NOAA** [comment]
MOAR PUPPIESSSS!

**Comment by SRBayer** [comment]
![download](https://github.com/user-attachments/assets/7982239f-c23b-4271-b3f0-7a92af3273a5)

**Comment by eeholmes** [comment]
![Sept 2008](https://github.com/user-attachments/assets/3dd33ba5-e989-4925-9999-b4c6f62119a8)

**Comment by stefaniebutland** [comment]
Best pups.  I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
