### ISSUE TITLE
Figure out how to predict the effects of a warming GOA on larval pollock survival

### ISSUE THREAD

**Issue by hwfennie** [nmfs-openscapes/2024-nmfs-champions#34]
Hi @pingercod and @somros,

This is what I hope my career will help answer and I need you two to help. 

## Here are two tasks that will be really helpful:

- [ ] 1. Develop a predictive model for larval pollock condition based on lipid content of large and small copepods (@pingercod 
- [ ] 2. Provide an ecosystem model predicting changes in producitivity of the GOA (@somros)

Thanks,

Will

**Comment by eeholmes** [comment]
To predict the effects of a warming Gulf of Alaska (GOA) on larval pollock survival, a comprehensive research plan can include the following steps:

### 1. **Define Research Objectives**
   - **Primary Objective**: To determine how increasing sea temperatures in the GOA impact the survival rate of larval pollock.
   - **Secondary Objective**: To investigate how associated changes (e.g., prey availability, predator abundance, ocean acidification) impact larval pollock survival.

### 2. **Literature Review**
   - Conduct a detailed review of existing studies on pollock life cycles, larval survival, and responses to environmental changes.
   - Identify gaps in existing research on the effects of warming oceans on marine life, especially in the GOA.

### 3. **Data Collection**
   - **Historical Data**: Gather historical data on sea surface temperatures (SST), currents, and other oceanographic parameters in the GOA. Remote-sensing platforms like MODIS or buoy-based systems can provide this data.
   - **Pollock Biology Data**: Collect existing biological data on larval pollock, such as growth rates, survival, feeding habits, and predator-prey dynamics under varying conditions.
   - **Ecological Data**: Obtain data on key prey species (e.g., zooplankton abundance) and predator distributions to explore changes in food webs driven by warming.

### 4. **Field Surveys**
   - **Sampling**: Conduct larval sampling in the GOA over time to assess seasonal and interannual variability in pollock populations. Use plankton tows, temperature-depth recorders, and nutrient profiling equipment.
   - **Oceanographic Monitoring**: Install or utilize ocean monitoring stations to measure temperature, salinity, and oxygen levels in larval pollock habitats.
   - **Experimental Design**: Set up controlled laboratory experiments to test how different temperature regimes affect larval development, growth rates, and mortality.

### 5. **Predictive Modeling**
   - **Climate Projections**: Use climate models to project sea temperature changes under various warming scenarios (e.g., IPCC RCP scenarios). Incorporate future projections for the GOA region.
   - **Population Models**: Develop a species-specific bioenergetic or population dynamics model to simulate the effects of warming temperatures on larval pollock. The model can incorporate temperature-dependent growth and mortality rates, prey availability, and predation pressures.
   - **Machine Learning**: Explore machine learning approaches to predict larval survival by integrating complex datasets, such as SST, zooplankton biomass, ocean currents, and historical survival rates.

### 6. **Statistical Analysis**
   - Conduct regression or time-series analyses to link changes in ocean conditions with historical larval survival data.
   - Investigate potential thresholds where temperature changes lead to significant drops in survival rates.

### 7. **Sensitivity and Uncertainty Analysis**
   - Perform sensitivity analysis to identify which factors (e.g., temperature, food availability, predation) have the greatest impact on larval survival.
   - Assess uncertainties in the predictions by testing different climate scenarios and biological responses.

### 8. **Evaluate Ecological and Socioeconomic Impacts**
   - Determine the broader ecological consequences of reduced pollock recruitment, such as effects on GOA food webs and commercial fisheries.
   - Engage stakeholders (e.g., fisheries managers) to explore management strategies in response to changing pollock populations.

### 9. **Dissemination of Findings**
   - Publish results in peer-reviewed journals.
   - Present findings at conferences or in collaboration with resource management agencies.
   - Provide recommendations for future monitoring or adaptive management of the GOA ecosystem and pollock fishery.

This plan integrates field data, predictive models, and the latest climate projections to generate actionable insights for the survival of larval pollock in the GOA.

**Comment by pingercod** [comment]
> Hi @pingercod and @somros,
> 
> This is what I hope my career will help answer and I need you two to help.
> 
> ## Here are two tasks that will be really helpful:
> * [ ]  1. Develop a predictive model for larval pollock condition based on lipid content of large and small copepods (@pingercod
> * [ ]  2. Provide an ecosystem model predicting changes in producitivity of the GOA (@somros)
> 
> Thanks,
> 
> Will

**Comment by hwfennie** [comment]
Thank you @eeholmes !

Will
