### ISSUE TITLE
I would like more ☕ please

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [nmfs-openscapes/2024-nmfs-champions#41]
**Is your feature request related to a problem? Please describe.**
I am tired

**Describe the solution you'd like**
I would like to drink coffee

**Describe alternatives you've considered**
🍵  

**Additional context**
Hi @jackiewilson-noaa and @jeffsmith7

**Comment by HBaertl** [comment]
> Popping by to say I think this is a top priority

I second this

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
