### ISSUE TITLE
Please show me pictures of your pets

### ISSUE THREAD

**Issue by abigailgolden-noaa** [nmfs-openscapes/2024-nmfs-champions#44]
@TMcCulloch-NOAA and @badgerjj, would you please share pictures of your 🐈 or 🐶

**Comment by RichMcBride** [comment]
how is this 
![MePcarolinusJune2023](https://github.com/user-attachments/assets/eca3bb45-d547-4a78-8658-42cc2539546f)

**Comment by badgerjj** [comment]
![64C52422-0157-488A-91BD-6E092569D137_1_105_c](https://github.com/user-attachments/assets/b7895f25-25aa-4733-bc04-0ad0b62dc049)

**Comment by TMcCulloch-NOAA** [comment]
![image](https://github.com/user-attachments/assets/5190a888-a874-480a-a420-5380ccc40c92)
