### ISSUE TITLE
Issue practice

### ISSUE THREAD

**Issue by jeffsmith7** [nmfs-openscapes/2024-nmfs-champions#45]
@ChristineStawitz-NOAA @jackiewilson-noaa practicing this tagging and issue creation exercise.  

# try creating a list

- [ ] step 1
- [ ] step 2

I wonder how to add an emoji in markdown

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
