### ISSUE TITLE
URGENT - this is a very pressing question about PETS

### ISSUE THREAD

**Issue by hsynan** [nmfs-openscapes/2024-nmfs-champions#47]
If you have **pets**, what are their names? (*pictures encouraged* :D )

**Comment by hsynan** [comment]
I have two **DOGS**, coco and skipper

**Comment by kstierhoff** [comment]
I have two cats, Trip (orange) and Magic (black).

![cats](https://github.com/user-attachments/assets/bdb0f510-bfce-477f-a2f8-d646689e0d4b)

**Comment by jules32** [comment]
My dog's name is Khora

**Comment by mkbrooks808** [comment]
![IMG_9696](https://github.com/user-attachments/assets/3a7fa7de-c68b-4d84-b1e5-2f009e9b65d5)

This is Buck

**Comment by hsynan** [comment]
Thank you all for your contributions to this very rewarding work

**Comment by HBaertl** [comment]
> ![IMG_9696](https://private-user-images.githubusercontent.com/38666481/379414563-3a7fa7de-c68b-4d84-b1e5-2f009e9b65d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDc4NzEsIm5iZiI6MTcyOTcwNzU3MSwicGF0aCI6Ii8zODY2NjQ4MS8zNzk0MTQ1NjMtM2E3ZmE3ZGUtYzY4Yi00ZDg0LWIxZTUtMmYwMDllOWI2NWQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE4MTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZjIyMTMwMTI1NzdiMTYzNmJlNWYwNjhjNzI4MDg0NDZhM2Y1NWU2Zjk5ZDYzMjU0MTc3OWMwNGRjN2UxMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OqQ-22xsPOndcQpGVq-v6ST32qwiLmjvUby3E60HFEE)
> 
> This is Buck

Beautiful picture!! Where was this taken?

**Comment by mkbrooks808** [comment]
@hsynan Thanks! That's a ridgeline in Juneau, AK where we live (between _Mount Roberts_ and _Sheep Mountain_)

**Comment by hsynan** [comment]
@mkbrooks808 **WOW** thats *amazing*! Buck is very lucky!

**Comment by HBaertl** [comment]
I have a rescue named Pepper Potts. She and I are the only 'girls' in a house with all boys
![51876](https://github.com/user-attachments/assets/6f03bdc8-d2ff-4b20-b177-84b81edb461f)

**Comment by HBaertl** [comment]
> @hsynan Thanks! That's a ridgeline in Juneau, AK where we live (between _Mount Roberts_ and _Sheep Mountain_)

wow! Love it!!!

**Comment by stefaniebutland** [comment]
The best pets! 
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
