### ISSUE TITLE
practice issues

### ISSUE THREAD

**Issue by emilyfergusson** [nmfs-openscapes/2024-nmfs-champions#48]
#Practicing with issues

testing

- [ ] task lists

- lists

@kstierhoff @hsynan

**Comment by kstierhoff** [comment]
I think that if you add a "space" in your header, you'll get the appropriate heading:

# Practicing

**Comment by hsynan** [comment]
## issues
### are 
#### fun

**Comment by emilyfergusson** [comment]
# practice
