### ISSUE TITLE
A question about the data

### ISSUE THREAD

**Issue by stefaniebutland** [nmfs-openscapes/2024-nmfs-champions#5]
## Questions

- [ ] thing 1
- [ ] thing 2

@jules32 Can you please help?

**Comment by jules32** [comment]
Great question. 

Maybe these lines of code would help: 

https://github.com/tidyverse/ggplot2/blob/main/R/autoplot.R#L14-L19

**Comment by stefaniebutland** [comment]
thanks @jules32
