### ISSUE TITLE
Writing an issue for Breakout Room 1

### ISSUE THREAD

**Issue by kngoodman** [nmfs-openscapes/2024-nmfs-champions#50]
Practice! :) @keithhernandez-NOAA @kelsjames

**Comment by kelsjames** [comment]
You got it!

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
