### ISSUE TITLE
Breakout Group 7 Cohort B

### ISSUE THREAD

**Issue by DavidBaldwin-noaa** [nmfs-openscapes/2024-nmfs-champions#51]

**Comment by DavidBaldwin-noaa** [comment]
Need to practice issues.

@jessicac-noaa

**Comment by DavidBaldwin-noaa** [comment]
Adding Alicia

@AliciaGodersky-NOAA

**Comment by AliciaGodersky-NOAA** [comment]
Thanks David! You're ahead of the game

**Comment by AliciaGodersky-NOAA** [comment]
LOVE Jessica's suggestion to make a filter w/in email for GitHub

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
