### ISSUE TITLE
How is your dog doing?

### ISSUE THREAD

**Issue by sbreitbart-NOAA** [nmfs-openscapes/2024-nmfs-champions#53]
Just wondering! @stefaniebutland 🐕

**Comment by jessicac-noaa** [comment]
She is okay, more testing required

**Comment by AliciaGodersky-NOAA** [comment]
Glad to hear <3

**Comment by stefaniebutland** [comment]
Ruby's great! Thanks for asking @sbreitbart-NOAA 
![rubyvert2](https://github.com/user-attachments/assets/4fb38d9d-cdf6-4b4a-8c14-73f833616140)
