### ISSUE TITLE
Solution to AKR data crisis

### ISSUE THREAD

**Issue by cathytide** [nmfs-openscapes/2024-nmfs-champions#55]
There's a data crisis at the Alaska Region.  Can I please have your help on this issue? 

- [ ] @bkallay - will you bring the nachos?   
- [x] @natashahowe - there's a gallon of salsa in the fridge; can you bring it from the break room?

**Comment by dpendleton1** [comment]
You are going to need *coffee* and probably *seltzer* water, too, in order to address this crisis.
