### ISSUE TITLE
trying to create an issue

### ISSUE THREAD

**Issue by jackiewilson-noaa** [nmfs-openscapes/2024-nmfs-champions#56]
I am creating a new issue. I am tagging @ChristineStawitz-NOAA and @jeffsmith7 

- [x] create issue (check)
- [x] submit new issue (check)

**Comment by ChristineStawitz-NOAA** [comment]
@jackiewilson-noaa hi

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
