### ISSUE TITLE
Breakout group 5 Issue Practice

### ISSUE THREAD

**Issue by mkbrooks808** [nmfs-openscapes/2024-nmfs-champions#58]
### Practice with Issues

- [ ] Add new issue
- [ ] include tags
- [ ] submit for review

Please review and give feedback @matthew-odell @HBaertl @jules32

**Comment by matthew-odell** [comment]
This looks good to me!

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
