### ISSUE TITLE
More bold text

### ISSUE THREAD

**Issue by kelsjames** [nmfs-openscapes/2024-nmfs-champions#59]
**We're seriously underusing bolded text in our project. Let's fix that!**
@keithhernandez-NOAA 
@kngoodman

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
