### ISSUE TITLE
Practice Issue question

### ISSUE THREAD

**Issue by cberchok** [nmfs-openscapes/2024-nmfs-champions#6]
## I have a question with what Stephanie said

* She included Julie in the message and assigned it to her, but then she was talking about pasting URL to flag it.  Is that needed?

@eeholmes

**Comment by eeholmes** [comment]
Hmm, I missed that part.

**Comment by stefaniebutland** [comment]
Hi @cberchok. Good question. I didn't need to paste the url anywhere to flag it. To get Julie's attention I needed to either assign the issue to her, or tag her in the issue, or if she wasn't a GitHub user, I could share the url with her to share the info.

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
