### ISSUE TITLE
What will you be for Halloween

### ISSUE THREAD

**Issue by Molly-Zaleski** [nmfs-openscapes/2024-nmfs-champions#60]
Send me you Halloween costume inspiration

![unnamed](https://github.com/user-attachments/assets/0e7fee18-5d82-4001-b9e8-13679cdb96f4)

**Comment by alaiam** [comment]
What is the costume of the two persons in red? I like it @Molly-Zaleski

**Comment by jules32** [comment]
Amazing issue, top priority. My nieces are being greek gods & godesses and my sister in law is Medusa

**Comment by Molly-Zaleski** [comment]
The red costumes are deep sea tube worms, including our own @abby-jahn!
