### ISSUE TITLE
The equation in Eli.md has error

### ISSUE THREAD

**Issue by eeholmes** [nmfs-openscapes/2024-nmfs-champions#62]
https://github.com/nmfs-openscapes/2024-nmfs-champions/blob/a6d98192c3f5885127e07a576b17ff811f782a5e/github-clinic/eli.md?plain=1#L13

Need help

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
