### ISSUE TITLE
opinion request

### ISSUE THREAD

**Issue by natashahowe** [nmfs-openscapes/2024-nmfs-champions#63]
I have a very important question. What is your favorite season?

- [ ] spring
- [x] summer
- [ ] fall
- [ ] winter

@cathytide @bkallay

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
