### ISSUE TITLE
issue regarding coffee

### ISSUE THREAD

**Issue by dpendleton1** [nmfs-openscapes/2024-nmfs-champions#64]
We need some more caffeinated coffee and good oat milk. Can somebody help out with that by going to the store this afternoon?

**Comment by kstierhoff** [comment]
Our store doesn't have oat milk and only decaffeinated coffee. It's a horrible store, actually. Sorry I can't help with this one!

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
