### ISSUE TITLE
This list has an error 

### ISSUE THREAD

**Issue by alicebeittel** [nmfs-openscapes/2024-nmfs-champions#67]
https://github.com/nmfs-openscapes/2024-nmfs-champions/blob/a6d98192c3f5885127e07a576b17ff811f782a5e/github-clinic/alice.md?plain=1#L25-L29

Cakes needs to be #1.

**Comment by kelsjames** [comment]
Yes, need to add coffee to this grocery list :)

**Comment by alicebeittel** [comment]
@bdschwartzkopf Do you have input on this very important issue???

**Comment by bdschwartzkopf** [comment]
We obviously need to add ingredients to make tacos

**Comment by alicebeittel** [comment]
Reopen issue

**Comment by alicebeittel** [comment]
Reopen

**Comment by alicebeittel** [comment]
Fixed issue

**Comment by alicebeittel** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

Was trying this but now I see I think I need to reference an issue

**Comment by alicebeittel** [comment]
Resolved #67
