### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by IsabellaGarfield** [nmfs-openscapes/2024-nmfs-champions#7]
### There is a problem!

*I don't know exactly what it is*

@jmjech help!

**Comment by jmjech** [comment]
Oh no! 
I may be able to help...

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
