### ISSUE TITLE
Bugaboos

### ISSUE THREAD

**Issue by HBaertl** [nmfs-openscapes/2024-nmfs-champions#70]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the debugging guide: <https://github.com/Openscapes/2021-noaa-nmfs/wiki/2-Issues-and-Project-Boards>
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue isn't already filed.

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
