### ISSUE TITLE
Breakout Group 5 test issue

### ISSUE THREAD

**Issue by HBaertl** [nmfs-openscapes/2024-nmfs-champions#71]
@matthew-odell 
@jules32

**Comment by jules32** [comment]
Matthew shows us the filter bar up top and how that helps you navigate to find what you need!

**Comment by matthew-odell** [comment]
Let's add @mkbrooks808

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
