### ISSUE TITLE
A question about our data

### ISSUE THREAD

**Issue by stefaniebutland** [nmfs-openscapes/2024-nmfs-champions#73]
## Questions

- [ ] #74
- [ ] #107

Can you please help @jules32

**Comment by jules32** [comment]
Great question. 

Maybe these lines of code could help --> cool that this highlights specific lines: 

https://github.com/tidyverse/ggplot2/blob/main/R/aes.R#L4-L8

**Comment by stefaniebutland** [comment]
thanks for the hdlp
