### ISSUE TITLE
Testing to create an issue

### ISSUE THREAD

**Issue by HChan-PIFSC** [nmfs-openscapes/2024-nmfs-champions#76]
Hi @pwoodworth-jefcoats, can you help me with this exercise?

**Comment by pwoodworth-jefcoats** [comment]
I see your issue!

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
