### ISSUE TITLE
Here is a new issue

### ISSUE THREAD

**Issue by heathernicholas** [nmfs-openscapes/2024-nmfs-champions#79]
can you please see about when the company will be able to install the equipment? thanks. @ateucher 

- [x] item 1
- [x] item 2

**Comment by ateucher** [comment]
Got it @heathernicholas thanks for the heads up. It will be ready Marchtember oneteenth.

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
