### ISSUE TITLE
Practice issue!

### ISSUE THREAD

**Issue by JZeh1** [nmfs-openscapes/2024-nmfs-champions#8]
Practicing making an issue in breakout rooms

- [x] task 1
- [ ] task 2

@brian-lieb @emmonsca

**Comment by jules32** [comment]
Great list! Check out #5 , seems relevant

**Comment by brian-lieb** [comment]
It certainly seems like you can make an issue.  Great job @JZeh1 

I guess we are supposed to _practice_ using markdown, so I will add a numbered list too:

1. Adding 
2. A
3. Numbered
4. List
5. To 
6. This 
7. Comment
