### ISSUE TITLE
My dog is whining at me

### ISSUE THREAD

**Issue by emchuron** [nmfs-openscapes/2024-nmfs-champions#82]
Suggestions @RyanRykaczewski-NOAA

**Comment by eeholmes** [comment]
![Sept 2008](https://github.com/user-attachments/assets/baf369e4-eccf-4ae1-bb6d-8158c91d2a3c)

**Comment by RyanRykaczewski-NOAA** [comment]
Give that dog some treats!

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
