### ISSUE TITLE
Help with eqn code in eli.md

### ISSUE THREAD

**Issue by eeholmes** [nmfs-openscapes/2024-nmfs-champions#84]
https://github.com/nmfs-openscapes/2024-nmfs-champions/blob/1eb2f4ad4bce577d1da27c1c831fc2478bbc54dd/github-clinic/eli.md?plain=1#L11-L13

@RyanRykaczewski-NOAA Can you help with my equation code. I am lost

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
