### ISSUE TITLE
Creating a test issue

### ISSUE THREAD

**Issue by GaitlynMalone-NOAA** [nmfs-openscapes/2024-nmfs-champions#85]
### **Task List**
- [x] Task 1
- [ ] Task 2

Test @LorenStearmanNOAA

**Comment by LorenStearmanNOAA** [comment]
I vote task 1!

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
