### ISSUE TITLE
What's the best choice?

### ISSUE THREAD

**Issue by Ashley-Trudeau-NOAA** [nmfs-openscapes/2024-nmfs-champions#9]
A vacation at: 
- [ ] The beach
- [x] The mountains
- [ ] The city

@tracymercer-noaa

**Comment by stefaniebutland** [comment]
I'm closing this issue so the other Cohorts can have a "fresh start", but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
