### ISSUE TITLE
I've got Issues!!

### ISSUE THREAD

**Issue by alemickle** [nmfs-openscapes/2024-nmfs-champions#91]
My issues is that I don't know much coding and this is my first time using GitHub 😨 👽 

Thought so far:

- I learn by doing and the instructions help
- Doesn't seem to dificult
- I  may regret that later

@MargaretSiple-NOAA and @MeghanParsley-NOAA do you agree?

**Comment by MeghanParsley-NOAA** [comment]
I like the features, but still seems intimidating! Excited to finally be learning github after coding for many years

**Comment by stefaniebutland** [comment]
I love this issue!!

I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
