### ISSUE TITLE
Breakout room 3 Sample Issue

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-openscapes/2024-nmfs-champions#92]
Sample Issue with breakout room 3

## Issue

1. Biggest issue is that I don't know much (Ben) :)
2. Add a Label 
3.
4.

## Solution 

@cgredzens-NOAA @efletcherPIFSC @bensandford

**Comment by cgredzens-NOAA** [comment]
It lives! @efletcherPIFSC 

- [ ] Get Ben added

**Comment by bensandford** [comment]
I see the issue

**Comment by bensandford** [comment]
I see it says 'soltion', not 'solution' :)
