### ISSUE TITLE
Would you rather?

### ISSUE THREAD

**Issue by MeghanParsley-NOAA** [nmfs-openscapes/2024-nmfs-champions#93]
Would you rather...

1. have a dog that can talk
OR
3. a cat that can pay half the rent?

 :speech_balloon:

@MargaretSiple-NOAA 
@alemickle

**Comment by MargaretSiple-NOAA** [comment]
Definitely a cat that can pay half the rent! The cat community owes me big time 😂

**Comment by eeholmes** [comment]
a cat that can pay half the rent! I think my dog would drive me nuts if she could talk.

**Comment by eeholmes** [comment]
![image](https://github.com/user-attachments/assets/e0797103-2477-45d8-8a83-dbb602da5ce7)

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but this is one that's so hard to close ❤️ . 

You can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
