### ISSUE TITLE
Living with fumes

### ISSUE THREAD

**Issue by TheaTCJ** [nmfs-openscapes/2024-nmfs-champions#94]
- [x] Go outside
- [ ] Stay home
- [x] Leave work early
- [x] masks??
@a-larval-schmidt 
@jonwhit

**Comment by a-larval-schmidt** [comment]
masks are essential

**Comment by RyanRykaczewski-NOAA** [comment]
Hold your breath!!!

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
