### ISSUE TITLE
There is a cat obstructing my screen-- is this a bug or a feature?

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [nmfs-openscapes/2024-nmfs-champions#96]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the debugging guide: <https://github.com/Openscapes/2021-noaa-nmfs/wiki/2-Issues-and-Project-Boards>
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue isn't already filed.

### Description

Problem: cat crossing screen

### Steps to Reproduce

1. I sit at my desk
2. I try to do one thing
3. Cat walks

**Expected behavior:**

I guess this IS expected behavior!

**Actual behavior:**
![IMG_3386](https://github.com/user-attachments/assets/e3e4312c-05ce-4e13-a46f-e16c3621b192)

**Reproduces how often:**

All de time.

**Comment by MargaretSiple-NOAA** [comment]
@alemickle this is a test - did you get a notification?

**Comment by stefaniebutland** [comment]
Another one that's so hard to close ❤️ . 

I'm closing the practice issues from the GitHub Clinic, but you can always re-open it, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
