### ISSUE TITLE
its just a small issue

### ISSUE THREAD

**Issue by CamVanHorn-NOAA** [nmfs-openscapes/2024-nmfs-champions#98]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
