### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by ChrisAnderson-NOAA** [nmfs-openscapes/2024-nmfs-champions#99]
## Coding Bugs that need to be fixed

There are a few issues with the current project that need to be correct;

1.  Please verify that the following link works [Important Link](https://www.youtube.com/watch?v=xm3YgoEiEDc) @MargaretSiple-NOAA, @DavidLandsman 
2. Report back the results!

**Comment by DavidLandsman** [comment]
important link verified

**Comment by stefaniebutland** [comment]
I'm closing the practice issues from the GitHub Clinic, but you can always re-open this, and come back to this [2024-nmfs-champions](https://github.com/nmfs-openscapes/2024-nmfs-champions) repo to use as a sandbox for trying things.
